using System;
using System.IO;
using UnityEngine;

namespace BodyRig.ReferenceRenderer
{
    /// <summary>
    /// Reads build-time provenance embedded into the physical reference player.
    /// The resource is generated by the Unity build entry point from the exact
    /// clean BodyRig Git revision supplied by build-reference-renderer.ps1.
    /// It is deliberately not accepted from runtime command-line arguments.
    /// </summary>
    public static class BodyRigBuildProvenance
    {
        private const string ResourceName = "bodyrig-build-provenance";

        [Serializable]
        private sealed class BuildProvenance
        {
            public string format;
            public int version;
            public string bodyrig_revision;
        }

        public static string RequireRevision()
        {
            var asset = Resources.Load<TextAsset>(ResourceName);
            if (asset == null)
            {
                throw new InvalidDataException("BodyRig player has no embedded build provenance resource");
            }

            BuildProvenance provenance;
            try
            {
                provenance = JsonUtility.FromJson<BuildProvenance>(asset.text);
            }
            catch (Exception exception)
            {
                throw new InvalidDataException("Embedded BodyRig build provenance is not valid JSON", exception);
            }

            if (provenance == null || provenance.format != "bodyrig-build-provenance" || provenance.version != 1)
            {
                throw new InvalidDataException("Unsupported embedded BodyRig build provenance format/version");
            }

            var revision = provenance.bodyrig_revision;
            if (!IsLowerHexGitSha(revision))
            {
                throw new InvalidDataException("Embedded BodyRig build provenance has an invalid Git revision");
            }
            return revision;
        }

        private static bool IsLowerHexGitSha(string value)
        {
            if (string.IsNullOrEmpty(value) || value.Length != 40) return false;
            foreach (var character in value)
            {
                if (!((character >= '0' && character <= '9') || (character >= 'a' && character <= 'f'))) return false;
            }
            return true;
        }
    }
}
