from pathlib import Path

source = Path("bodyrig/photoidentity_evidence.py")
text = source.read_text(encoding="utf-8")
old = '''def _finite(value: object, *, label: str, minimum: float = 0.0, maximum: float = 1.0) -> float:\n    if isinstance(value, bool) or not isinstance(value, (int, float)):\n        raise PhotoIdentityEvidenceError(f"{label} is not numeric")\n    result = float(value)\n    if not math.isfinite(result) or not minimum <= result <= maximum:\n        raise PhotoIdentityEvidenceError(f"{label} is outside {minimum}..{maximum}")\n    return result\n'''
new = '''def _finite(value: object, *, label: str, minimum: float = 0.0, maximum: float = 1.0) -> float:\n    if isinstance(value, bool) or not isinstance(value, (int, float)):\n        raise PhotoIdentityEvidenceError(f"{label} is not numeric")\n    try:\n        result = float(value)\n    except OverflowError:\n        raise PhotoIdentityEvidenceError(f"{label} is outside {minimum}..{maximum}") from None\n    if not math.isfinite(result) or not minimum <= result <= maximum:\n        raise PhotoIdentityEvidenceError(f"{label} is outside {minimum}..{maximum}")\n    return result\n'''
if text.count(old) != 1:
    raise SystemExit("_finite source needle did not match exactly once")
text = text.replace(old, new)
old = '''    start = value.get("start_seconds")\n    duration = value.get("duration_seconds")\n    if isinstance(start, bool) or not isinstance(start, (int, float)) or not math.isfinite(float(start)) or float(start) < 0.0:\n        raise PhotoIdentityEvidenceError("photoidentity observation start is invalid")\n    if isinstance(duration, bool) or not isinstance(duration, (int, float)) or not math.isfinite(float(duration)) or not 1.0 <= float(duration) <= 12.0:\n        raise PhotoIdentityEvidenceError("photoidentity observation duration is invalid")\n'''
new = '''    start = value.get("start_seconds")\n    duration = value.get("duration_seconds")\n    if isinstance(start, bool) or not isinstance(start, (int, float)):\n        raise PhotoIdentityEvidenceError("photoidentity observation start is invalid")\n    try:\n        start_number = float(start)\n    except OverflowError:\n        raise PhotoIdentityEvidenceError("photoidentity observation start is invalid") from None\n    if not math.isfinite(start_number) or start_number < 0.0:\n        raise PhotoIdentityEvidenceError("photoidentity observation start is invalid")\n    if isinstance(duration, bool) or not isinstance(duration, (int, float)):\n        raise PhotoIdentityEvidenceError("photoidentity observation duration is invalid")\n    try:\n        duration_number = float(duration)\n    except OverflowError:\n        raise PhotoIdentityEvidenceError("photoidentity observation duration is invalid") from None\n    if not math.isfinite(duration_number) or not 1.0 <= duration_number <= 12.0:\n        raise PhotoIdentityEvidenceError("photoidentity observation duration is invalid")\n'''
if text.count(old) != 1:
    raise SystemExit("timing source needle did not match exactly once")
text = text.replace(old, new)
text = text.replace('''        "start_seconds": round(float(start), 3),\n        "duration_seconds": round(float(duration), 3),\n''', '''        "start_seconds": round(start_number, 3),\n        "duration_seconds": round(duration_number, 3),\n''')
source.write_text(text, encoding="utf-8")

tests = Path("tests/test_photoidentity_evidence.py")
text = tests.read_text(encoding="utf-8")
if "import hashlib\n" not in text:
    text = text.replace("import copy\n", "import copy\nimport hashlib\n", 1)
append = '''\n\ndef test_huge_row_timing_integer_fails_with_domain_error() -> None:\n    row = _row("scene1", "front")\n    row["start_seconds"] = 10**400\n\n    with pytest.raises(PhotoIdentityEvidenceError, match="photoidentity observation start is invalid"):\n        _evidence(capabilities=["coarse-face-view"], rows=[row])\n\n\ndef test_huge_quality_integer_fails_with_domain_error() -> None:\n    row = _row("scene1", "front")\n    row["target_confidence"] = 10**400\n\n    with pytest.raises(PhotoIdentityEvidenceError, match=r"target_confidence is outside 0\\.0\\.\\.1\\.0"):\n        _evidence(capabilities=["coarse-face-view"], rows=[row])\n\n\ndef test_bundle_huge_bound_numeric_fails_after_sha_binding(tmp_path: Path) -> None:\n    evidence = _evidence(\n        capabilities=["coarse-face-view", "coarse-full-body-view"],\n        rows=[_row("scene1", "front"), _row("scene2", "front")],\n    )\n    observations, report_path, _ = write_bundle(tmp_path / "bundle-overflow", evidence)\n\n    raw = json.loads(observations.read_text(encoding="utf-8"))\n    raw["rows"][0]["target_confidence"] = 10**400\n    observation_bytes = (json.dumps(raw, ensure_ascii=False, indent=2, sort_keys=True) + "\\n").encode("utf-8")\n    observations.write_bytes(observation_bytes)\n\n    report = json.loads(report_path.read_text(encoding="utf-8"))\n    report["observation_evidence_sha256"] = hashlib.sha256(observation_bytes).hexdigest()\n    report_path.write_text(\n        json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\\n",\n        encoding="utf-8",\n    )\n\n    with pytest.raises(PhotoIdentityEvidenceError, match=r"target_confidence is outside 0\\.0\\.\\.1\\.0"):\n        validate_bundle(report_path, observations)\n'''
if "test_huge_row_timing_integer_fails_with_domain_error" not in text:
    tests.write_text(text.rstrip() + append.rstrip() + "\n", encoding="utf-8")
